### ISSUE TITLE
Can it print byte buffers annotated with `#[serde(with = "serde_bytes")]` more nice?

### ISSUE THREAD

**Issue by vi** [RReverser/serdebug#1]
Currently they looks like usual `[65, 66, 67, 68, 69, 70, 71]` instead of something more useful like `b"ABCDEFG"` or `b"\x41\x42\x43\x44\x45\x46\x47"`.

**Comment by RReverser** [comment]
Saw this _very_ late, but if anyone comes across this question, I think you just need a different `serde(with)` for this usecase.
